# Generated by Django 4.0.3 on 2022-03-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azonosito', models.IntegerField()),
                ('nev', models.CharField(max_length=256)),
                ('szak', models.CharField(max_length=256)),
                ('pont', models.IntegerField()),
                ('megfelelt', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Diák',
                'verbose_name_plural': 'Diákok',
            },
        ),
    ]
