# Generated by Django 4.0.3 on 2022-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diak',
            name='megfeleltt',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
